### ISSUE TITLE
support beam info and beam rendering from an AIPS fits cube

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1083]
example AIPS fits images can be obtained from https://www2.mpia-hd.mpg.de/THINGS/Data.html

For such AIPS fits images, the beam info is not represented in header as BMAJ, BMIN, and BPA. It adopted a non-standard representation using the HISTORY keyword. The "standard" AIPS form is (all in degrees)

`HISTORY AIPS   CLEAN BMAJ=  3.8158E-03 BMIN=  3.4928E-03 BPA= -40.24 = `

We should still try to look for BMAJ, BMIN, and BPA to set up beam info. If those are not available, then look for that specific HISTORY to guess the beam shape for the file info (hence the frontend can render the beam properly).

[HO_II_NA_MOM0_THINGS.FITS.zip](https://github.com/CARTAvis/carta-backend/files/8469578/HO_II_NA_MOM0_THINGS.FITS.zip)

detailed discussions in https://docs.google.com/document/d/1qUm02JOLxOoG_4p_lDJpKRj7z4tnwsEh5GoOxASKNSs/edit#

Let's do 1 and 2 as described in the doc

The frontend counterpart is https://github.com/CARTAvis/carta-frontend/issues/2164

**Comment by kswang1029** [comment]
@markccchiang do you have time to look into this?

**Comment by markccchiang** [comment]
> @markccchiang do you have time to look into this?

Ok, I will take a look at it.

**Comment by pford** [comment]
This is supported in casacore, but for #935 we removed the HISTORY beam. (See FitsLoader::RemoveHistoryBeam)

My comments in #935 indicated it was for AIPS images according to the casacore::FITSImage header comments.

**Comment by kswang1029** [comment]
@jott3077 made this request to support AIPS fits cube. Deriving beam shape from history is really not ideal but we have no other choices. #935 is an example demonstrating it can lead to bad results. 

Maybe we will need to warn users in the file info if the beam info is derived from history 🤔️

**Comment by veggiesaurus** [comment]
This is rather frustrating, because history is really not the appropriate place for this information, and the user was quite right to ask us to ignore it. If we add this back, we may produce misleading results, surely?

**Comment by kswang1029** [comment]
@jott3077 could you confirm what unit is implicitly assumed for the beam shape defined in the HISTORY of an AIPS fits cube? #935 is an case that the unit is not set correctly by casacore, resulting an incorrect rendered beam. We have to make sure all AIPS fits cubes adopt the same unit for beam shape definition, otherwise rendering a wrong beam element is worse than not showing a beam element.

**Comment by veggiesaurus** [comment]
> Deriving beam shape from history is really not ideal but we have no other choices.

I guess the other choice would be to ignore it and provide a scripting snippet to generate the appropriate beam headers from the history.

**Comment by kswang1029** [comment]
Can NRAO archive team fix this beam issue for all the archived AIPS fits images? This would help the situation a lot and ensure robustness for the future.

**Comment by jehibbard** [comment]
It's wider than the NRAO archive. For instance, I put all my thesis HI cubes and some subsequent ones into NED, and they have this behavior. 

I checked a bunch of ancient images I have on disk and found:

HISTORY AIPS CLEAN BMAJ=...

gives units of degrees

HISTORY APCLN BMAJS=

gives units of arcsec (so did "HISTORY CONVL BMAJ=" in the #935 example)

MIRIAD gave units explicitly:
HISTORY RESTOR: Beam =  7.277E+00 x  6.230E+00 arcsec, pa =  6.706E+01 degrees

The first (HISTORY AIPS CLEAN BMAJ=... with units in degrees) was by far the most common, at least from my experience. 

I agree that it would be a "nice to have" fall-back behavior to read it from the HISTORY card if the BMAJ fits keyword is missing, and print out a warning that it is falling back to this behavior and if the beam is wrong to set it explicitly using the BMAJ, BMIN, BPA fits keywords. 


That would not help the #935 example, where there are (at least) several different HISTORY*BMAJ ="  entries:
HISTORY PUTHEAD BMAJ = 0.00000E+00 / old
HISTORY PUTHEAD BMAJ = 5.55556E-04 / new
HISTORY CONVL BMAJ= 5.0000 BMIN= 5.0000 BPA= 0.0/Output beam
HISTORY AIPS CLEAN BMAJ= 1.3889E-03 BMIN= 1.3889E-03 BPA= 0.00
as well as:
HISTORY RESTOR Beam = 2.000E+00 x 1.800E+00 arcsec, pa = 8.000E+01 degrees

So I have no idea what the beam is for that image (my guess wold be that it would be the last entry rather than the first)

**Comment by veggiesaurus** [comment]
> So I have no idea what the beam is for that image (my guess wold be that it would be the last entry rather than the first)

Personally I think this is exactly why we shouldn't attempt to guess things unless they are following a clear and widely used convention. This looks like a minefield to me.

**Comment by veggiesaurus** [comment]
@markccchiang don't worry about this for now. It's on hold until there is clear consensus as to how we should handle this situation.
