### ISSUE TITLE
Handle regions outside image

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#110]
As specified in Regions 1.1 document 
https://docs.google.com/document/d/1IdEh2x7lrsul4kSJ3lzGCiEUyI9gGTX7yVp8BtCKUyw/edit#

when regions are outside the image (no data) the data streams for profiles and stats should return arrays of 0 (for histograms) or NaN (profiles and stats).

**Comment by veggiesaurus** [comment]
Possibly related: Currently, the backend returns a sum and mean of zero for regions containing only NaN pixels. In the example below, the channel around 1.42 GHz is bad, therefore full of NaNs. I think these values should be NaN instead of zero. @kswang1029 thoughts?

![image](https://user-images.githubusercontent.com/592504/55060626-8fc81f00-507a-11e9-807c-1f3e5a10dc3f.png)

**Comment by kswang1029** [comment]
Yes, if a region covers pixels all in NaN, we should return NaN.

**Comment by veggiesaurus** [comment]
> Possibly related: Currently, the backend returns a sum and mean of zero for regions containing only NaN pixels....

this seems to be fixed :+1:

**Comment by kswang1029** [comment]
Yes, it works well! 👍
