### ISSUE TITLE
Incorrect common beam estimation

### ISSUE THREAD

**Issue by spectram** [CARTAvis/carta-backend#1105]
**Describe the bug**
When reading an image with multiple beams (i.e beams per channel), the value displayed in carta seems different from the value obtained by using common_beam in spectral cube package. The common beam calculated by casa also seems to align with the latter value. 

**To Reproduce**
1. Load a fits file with 2 tables; one with the image data and the other with beams data.

**Expected behavior**
In the file information; carta shows a different value

**Screenshots or videos**
See fig 1 for multiple beams and fig 2 for common beam

**Platform info (please complete the following information):**
Any; I use carta-beta.idia.ac.za and carta.idia.ac.za

Fig1:
![fig1:beams-per-channel](https://user-images.githubusercontent.com/83280431/164991190-c8064530-0675-4f10-b6fa-29cdb82087bc.png)

Fig2:
![fig2:commonbeam](https://user-images.githubusercontent.com/83280431/164991191-21981c77-7526-4a8e-9ed5-6fb245cddd35.png)

**Comment by kswang1029** [comment]
@spectram could you provide a test image for us to investigate this issue?

**Comment by spectram** [comment]
Hi @kswang1029,

I am attaching a casa image and a fits cube of a cutout from a bigger image. These do not have BMAJ, BMIN, or BPA parameters in their headers. 

CARTA File information: smallcube
Median area beam = 19.2378" X 17.2745", -0.353488 deg
CARTA File information: smallcube.fits
Median area beam = 19.2378" X 17.2745", -1.40381 deg

SpectralCube Common_beam: smallcube.fits
Beam: BMAJ=19.249313704503244 arcsec BMIN=17.284865456849378 arcsec BPA=-20.25337028503418 deg

[smallcube.zip](https://github.com/CARTAvis/carta/files/8668002/smallcube.zip)

**Comment by kswang1029** [comment]
@spectram thanks for the test images. Using CASA-imhead (version 6.4.3.27) I see those images have BPA defined in _rad_. Our test image generated with earlier version of CASA is in _deg_. I guess at some point CASA changed the default unit of BPA. We also had a bug fix on this a few weeks ago, which will be available in the v3-beta3 release coming very soon. With that, I see the computed values of each image are consistent with what reported by CASA-imhead but the two have different computed BPA. This difference is also seen via CASA-imhead by checking each beam info at different channels. 

We will try to fix this for the final v3 release (due summer 2022).

**Comment by kswang1029** [comment]
@spectram using your test images, with CARTA **_v3b3_** release and CASA 6.4.3, I see consistent results. As for the inconsistent beam position angle, I think it is due to the unit issue (rad vs deg) and when converting between casa format and fits format, it went wrong. This issue should be handled by team responsible for the convertor I think. 

CARTA v3b3
casa image: `Median area beam = 19.2378" X 17.2745", -20.2534 deg`
fits image: `Median area beam = 19.2378" X 17.2745", -80.4326 deg`

CASA 6.4.3.27
casa image: `Median   19.2378 arcsec x   17.2745 arcsec pa=-20.2534 deg`
fits image: `Median   19.2378 arcsec x   17.2745 arcsec pa=-80.4326 deg`

Could we close this issue now?

**Comment by spectram** [comment]
Thanks for checking and getting back @kswang1029 
Closing the issue.
