### ISSUE TITLE
[region statistics] stats update when region is at subpixel scale

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#119]
NOT SURE THIS IS FROM THE FRONTEND OR THE BACKEND.
forgive me if this is issue is misplaced. 

See the demo, there are three movements of region after its creation. The second and third movement results in zero pixel inside the region but the stats values do not reflect this fact. 

![roi_stat](https://user-images.githubusercontent.com/20819712/55131144-61b90c80-5158-11e9-8e80-8760a7ee55dd.gif)

**Comment by veggiesaurus** [comment]
@kswang1029 have transferred issue to backend

**Comment by veggiesaurus** [comment]
printing out the casacore exception message that gets thrown: 
`LCBox::LCBox - blc [73, 30] must be <= trc [72, 30]`

**Comment by kswang1029** [comment]
rounding number!

**Comment by pford** [comment]
Issues #110, #118 (closed as duplicate), and #119 are the same issue: there is no SubLattice on which to calculate profiles/statistics.  This is either because the XYRegion does not exist (outside image or no pixels selected for very small region), or the Lattice mask applied to the SubLattice to remove NaN values leaves no pixels selected.  These issues will be fixed in the same branch to update the region data appropriately for an invalid/empty region.

**Comment by kswang1029** [comment]
Yes, it think it works beautifully! 👍
