### ISSUE TITLE
Save image bug with filepath

### ISSUE THREAD

**Issue by Jordatious** [CARTAvis/carta-backend#1252]
On the [IDIA CARTA server](https://carta.idia.ac.za) (running v3.0.1), I open one of the [THINGS](https://www2.mpia-hd.mpg.de/THINGS/Data.html) cubes (from `/carta_share/public/jcollier/THINGS/`), create a moment map or PV diagram, and then File --> Save image. In the file browser, when I try to save the image, a red box pops up with the following error msg: "Cannot save image type from loader.Directory: /carta_share/public/collier/THINGS does not exist and cannot be created". 

I then go back to the root directory and navigate back to the same directory, and save again, which is successful.

Even if I try to overwrite a file, a dialog pops up to mention the file exists and asks if I want to overwrite it, but attempting to save/overwrite it causes the same issue.

**Comment by kswang1029** [comment]
presumably this is a backend issue.

**Comment by kswang1029** [comment]
@veggiesaurus do you have time to have a look?

**Comment by kswang1029** [comment]
> @veggiesaurus do you have time to have a look (need the ilifu env to test)?

**Comment by confluence** [comment]
This is happening when the output directory path passed to the backend is absolute. Navigating all the way back to the root directory resets the path and all its children to relative paths. I suspect that the problem is that the absolute path is being passed to casacore as-is, and casacore is interpreting it as a valid absolute filesystem path (but it's not; it's relative to a root directory -- possibly this bug isn't triggered if the root directory is the filesystem root). I don't think that the absolute path input is incorrect (it works fine in the file list request), so we're probably missing a normalization step. I will investigate further how these paths are being handled.

**Comment by confluence** [comment]
More specific steps to reproduce:

1. launch carta with a top-level directory set
2. enable logging of SAVE FILE messages
3. create a PV image (moment map probably works too)
4. use the save image menu item to open the save dialog
5. in the file browser, make sure you're several directories deep from the top-level folder, and then click on a directory other than the top level directory in the breadcrumbs
6. try to save the file

Using the breadcrumbs to navigate to a directory prepends `/` to the path (and it is preserved when you use the filesystem list to navigate after that, but clicking on the top-level folder resets the path to `.` and after that the lack of leading `/` is preserved). This does not seem to happen if the top-level directory is set to the filesystem root. This form of the path doesn't seem to cause any problems with other types of requests, like fetching directory listings or opening images.
