### ISSUE TITLE
cannot animating polarization axis if frame rate is 1 or 2

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#1293]
**Describe the bug**
If we try to use the animator to animate the polarization axis with a frame rate of 1 or 2, it will just update 1 or 2 frames then stops. With a frame rate >=3, playback appears normal.

**To Reproduce**
1. load a Stokes cube
2. use the animator to select the polarization axis and set frame rate to 1 or 2 or 3+ to observe the behavior

**Expected behavior**
with a frame rate of 1 or 2, the playback function should be normal.

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS ventura
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 104
 - Backend branch [e.g. dev, v3b2 release]: dev
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Comment by acdo2002** [comment]
I did a quick test with ICD-RxJS/src/test/ANIMATOR_SWAPPED_IMAGES.test.ts by changing the FrameRate from 5 to 1.
However the ICD message cannot generate the manual situation. They are all passed with FrameRate of 1.
I check the frontend ICD message flow, it looks the backend frozen in these sequence.

> [2023-08-11 15:05:37.494] [CARTA] [debug] [protocol] <== ANIMATION_FLOW_CONTROL
> [2023-08-11 15:05:37.499] [CARTA] [debug] [protocol] <== ADD_REQUIRED_TILES
> [2023-08-11 15:05:37.569] [CARTA] [debug] [protocol] <== SET_SPATIAL_REQUIREMENTS

Because the ANIMATOR_SWAPPED_IMAGES.test.ts test does not include SET_SPATIAL_REQUIREMENTS (p.s. the ANIMATOR related ICD message flow does not include SET_SPATIAL_REQUIREMENTS ([link](https://carta-protobuf.readthedocs.io/en/latest/data_cube_navigation.html#animation))), not sure the problem is related to  SET_SPATIAL_REQUIREMENTS or not.

**Comment by kswang1029** [comment]
done in https://github.com/CARTAvis/carta-frontend/pull/2228
