### ISSUE TITLE
Feature suggestion: .cartaignore file

### ISSUE THREAD

**Issue by lh-astro** [CARTAvis/carta-backend#1334]
Some directories can sometimes be very crowded with files not intentioned to view in CARTA. It might be useful to defines two ignore settings/files in a similar way as the popular .gitignore file which can be used to hide files in the CARTA file browser:

1) A global ".cartaignore" file or setting within the CARTA interface and
2) a local .cartaignore file in the respective directory, which overwrites the global setting.

In addition the CARTA file browser could have a button or key shortcut the toggle between the ignore state.

**Comment by Jordatious** [comment]
Hey @lh-astro, this is an interesting idea, and I can see how this could be useful! Would you want to include image files that are readable by CARTA (FITS, CASA, etc) in your `.cartaignore` file(s)? If you didn't know, you can change how CARTA generates the file list in your global preferences (see attached), where "Filter by extension" will only list image files readable by CARTA based on their extension, which I think in the case of CASA (and miriad?) files is based on the directory contents. But including legitimate image files that you want to ignore sounds useful as well!
<img width="222" alt="image" src="https://github.com/CARTAvis/carta/assets/10542136/ae6bc37d-466d-4647-95e3-7860499e1f22">

**Comment by veggiesaurus** [comment]
@confluence this looks similar to the issue we were discussing yesterday

**Comment by confluence** [comment]
This sounds like a good idea. Our use case can be solved with a per-directory file, but for this use case it would be more useful to define defaults in a single central location (a git-like model). I think it makes sense for a per-directory `.cartaignore` to override the global settings.

The question is: 
1. where to put this global per-user file (the location should be immutable *and* accessible to the user both on SDM and UDM)
2. how easy it would be for us to resolve and match paths against patterns in a global file (rather than just per-directory) -- perhaps something like [this package](https://www.npmjs.com/package/ignore)?

I considered the starting directory, but that should be able to have its own local `.cartaignore` which should not double as global config, and also the starting directory varies depending on how the backend is launched. Off the top of my head, the most consistent and appropriate place would be a `.carta/cartaignore`, but SDM users don't have access to local config like this. Is there a more sensible location for user preferences that would work for an SDM install?

**Comment by veggiesaurus** [comment]
> but SDM users don't have access to local config like this. Is there a more sensible location for user preferences that would work for an SDM install?

My feeling is that SDM users would manage things using a per-directory cartaignore file. As an example, a user might create a `.cartaignore` file in a shared directory, masking out the `logs` directory and all `.log` files

**Comment by kswang1029** [comment]
see #1310
