### ISSUE TITLE
Importing and exporting of region definitions

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#171]
User needs to be able to:
- [ ] Import region definitions from CRTF
- [ ] Import region definitions from DS9 Region files
- [ ] Export region definitions to CRTF
- [ ] Export region definitions to DS9 Region files

Regions should be exportable in pixel or WCS coordinates

**Comment by kswang1029** [comment]
Regions should also be importable in pixel or wcs coordinates with sanity check.

If the wcs coordinates defined in the imported text file (e.g., fk5) are different from the coordinate system of the current view (e.g., galactic), transformation needs to be considered. 

If the text definition of a region in wcs coordinate has missing info (e.g., coordinate system), we will need to apply the coordinate system of the current view. Overall, we need to have a strategy to handle missing (non-critical) info of the input text file.

**Comment by pford** [comment]
https://docs.google.com/document/d/1gE2kCblsUzAisY8gqL_s3flSkEtupWqkQeRVLm6ikHc/edit

Import: need ICD change to proceed so that frontend can send filename (region file on server) or file contents (region file on client) to backend to parse, and response to frontend to render region.  Also specify whether region files will be added to existing file browser (done in branch pam/region_browser) or if a separate region browser will be used.

Export: need ICD change to request export with parameters, including filename (region file on server) and format.

**Comment by pford** [comment]
Closing this issue, now broken down into subtasks #285 , #286 , and #287 .
