### ISSUE TITLE
hdf5 cube histogram hangs 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#189]
from a general test I found that requesting a cube histogram from a hdf5 image hangs. In my test case, I have enabled statistics widget, spectral profiler widget, and histogram widget. A region is created and all the three widgets are set to that region. Then when I request the cube histogram, the dialog hangs. It is supposed to be instantly since the cube histogram should have been calculated and saved in the hdf5 image. 
![Screen Shot 2019-04-18 at 10.20.04 AM.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/583abdc9-48f8-46da-9f17-bdbf4036d2c9)

**Comment by veggiesaurus** [comment]
@kswang1029 I can't seem to reproduce this with the 1.1 branch. What file did you test this on?

**Comment by kswang1029** [comment]
please try http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev (frontend:dev, backend: dev)

try set_M17/M17_SWex.hdf5
I also tried with images in set_HDF5. issue remains.

**Comment by veggiesaurus** [comment]
Ok, can reproduce the bug. Strangely enough, it only occurs when you've requested a different region beforehand. 

And it's actually sending the correct data, but the `progress` and `regionId` fields haven't been set, which is why the frontend hangs. 

@confluence can you look into this? For cube histograms from HDF5 files' stats cache, `progress` should always be 1 (no partial updates) and the regionId should be set to `-2` to indicate the entire cube.

**Comment by veggiesaurus** [comment]
(from @kswang1029)
Steps to reproduce bug:

please try
1) load image
2) open histogram widget
3) make a region
4) change histogram widget to "region"
5) request cube histogram in render config
