### ISSUE TITLE
incorrect statistics of ellipse regions

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#216]
with the dev branch and using set_QA/M17_SWex.image as an example:

if an ellipse region is defined as: center_x = 114 px, center_y = 545 px, major = 4 px, minor = 2 px, at channel 0, the statistics are
![Screen Shot 2019-05-14 at 10 22 38 AM](https://user-images.githubusercontent.com/20819712/57666352-3ae46600-7632-11e9-8c5d-fbb8ef8b92f4.png)

But, with v1.1 release, the statistics are
![Screen Shot 2019-05-14 at 10 23 17 AM](https://user-images.githubusercontent.com/20819712/57666381-518abd00-7632-11e9-9768-c19dd149b1f0.png)

By double-checking with CASA-imstat, the statistics are
{'blc': array([112, 542,   0,   0], dtype=int32),
 'blcf': '18:20:26.776, -16.11.13.195, 8.67514e+10Hz, I',
 'flux': array([ 0.00851618]),
 'max': array([ 0.02505673]),
 'mean': array([ 0.00772359]),
 'medabsdevmed': array([ 0.0092781]),
 'median': array([ 0.00756571]),
 'min': array([-0.01768329]),
 'npts': array([ 24.]),
 'q1': array([-0.00210038]),
 'q3': array([ 0.01645581]),
 'quartile': array([ 0.0185562]),
 'rms': array([ 0.01397174]),
 'sigma': array([ 0.01189324]),
 'sum': array([ 0.18536625]),
 'sumsq': array([ 0.00468503]),
 'trc': array([116, 549,   0,   0], dtype=int32),
 'trcf': '18:20:26.665, -16.11.10.395, 8.67514e+10Hz, I'}

So it appears that the statistics from the current dev branch are not correct.

**Comment by ChristyReynolds** [comment]
I think I have this fixed today. I made changes to Region.cc so that statistics for the same ellipse calculated using imstat and CARTA match up. I want to see if I can get ellipses radii defined using world coordinates for another issue before issuing a pull request for this issue, but I have committed and pushed the changes I made to my feature branch.

**Comment by veggiesaurus** [comment]
@ChristyReynolds is this fixed and merged into `dev`? Can we close the issue?

**Comment by pford** [comment]
For now, we will keep the maj/min axes in pixel coordinates, since that is what the frontend sends.  This may need further work when implementing region imports and WCS groups.

I tested the region @kswang1029 described and got the statistics returned by version 1.1 and imstat.  Kuo-Song, does this ticket need further testing or shall we close it?

**Comment by kswang1029** [comment]
@pford @ChristyReynolds I verified with few images with different ellipse regions. Yes, now it is consistent with v1.1 and correct. Thanks. Close the issue.

However, I found another one related to statistics. Will file a new issue.
