### ISSUE TITLE
performance degradation of opening HDF5 images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#223]
With the dev branch as of May 22, 2019, there is performance degradation when opening HDF5 images. 
As an example,
set_IRAS_17150-3224/IRAS_17150-3224_sci.spw27.cube.I.manual.image.pbcor.fits (60GB) takes ~ 1.5 seconds, while its HDF5 format set_HDF5/IRAS_17150-3224_sci.spw27.cube.I.manual.image.pbcor.hdf5 (120GB) takes ~ 16 seconds (a factor of ~10 difference).

**Comment by veggiesaurus** [comment]
I initially thought it was due to reading histograms for all channels, but for the image you've tested, the histogram size is roughly 21 MB and can be read from disk in 12 sequential reads, so it really shouldn't account for the time difference.

**Comment by veggiesaurus** [comment]
Flame chart of `OnOpenFile` when loading FITS file (`OnOpenFile` takes 21 samples):
![image](https://user-images.githubusercontent.com/592504/58153870-7e615480-7c70-11e9-95da-5de9ae3ba67c.png)

Flame chart of `OnOpenFile` when loading equivalent HDF5 file (`OnOpenFile` takes **276 samples**):
![image](https://user-images.githubusercontent.com/592504/58153964-bec0d280-7c70-11e9-989a-78f275fcf466.png)

_Note: The `libc` call is incorrectly labelled due to a bug in valgrind. It's almost certainly a `malloc` call_

The loading of 2D stats and histograms happens after `OnOpenFile`, so I don't think that's the issue (took 26 samples). So there's definitely something odd going on with HDF5 files even when simply constructing the image object.

**Comment by veggiesaurus** [comment]
@pford it's the construction of the giant `casacore::ArrayLattice<bool>` in the `CartaHdf5Image` constructor that causes this issue. The array is created with the same dimensions as the entire cube, so in the case of the file @kswang1029 was trying, this is a 15 GB array. This makes HDF5 files (a) very slow to load and (b) unusable on limited memory machines. 

I understand that a mask is required for excluding NaNs, but this approach uses far too much memory. Below is a `psrecord` output for loading the same file in FITS (top) and HDF5 (bottom) format
![output_fits](https://user-images.githubusercontent.com/592504/58155192-b74ef880-7c73-11e9-95d2-e1709385b340.png)
![output_hdf5](https://user-images.githubusercontent.com/592504/58155195-b9b15280-7c73-11e9-9ed8-ce37fa08041c.png)
When trying to load a larger image (5850x1074x376), the memory really gets out of hand (again FITS top, HDF5 bottom)
![output_fits_galfacts](https://user-images.githubusercontent.com/592504/58155618-815e4400-7c74-11e9-88af-3e0feee261b1.png)
![output_hdf5_galfacts](https://user-images.githubusercontent.com/592504/58155318-ea918780-7c73-11e9-80e7-9679ce9848bd.png)

**Comment by pford** [comment]
@kswang1029 fix has been merged into dev and is ready for your review.  See graphs in pull request #229.

**Comment by kswang1029** [comment]
After checking with all available hdf5 images in the image pool, I think the issue is gone. Now opening an hdf5 image is as fast as other formats. 👍 Close this issue now.
