### ISSUE TITLE
overwrite of protocol buffer message leads to decoding errors, resulting in missing tiles

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#258]
with dev+dev branches (asiaa carta server)

**NOT SURE IT IS FRONTEND OR BACKEND**

it is possible to see missing tile through the following steps:
open public/set_noise/noise_11px_11px.fits
then open (not append) public/set_noise/noise_10px_10px.fits
We might see missing tile (in this case there is only one tile requested). If not, reload carta and repeat the above steps.

When I see the missing tile I also checked the js console, there is ADD_REQUIRED_TILES sent and REGION_HISTOGRAM_DATA returned but there is no RASTER_TILE_DATA returned.

**Comment by veggiesaurus** [comment]
@kswang1029 I've sort of figured out why this is occurring, and will update the issue name and add a comment shortly.

**Comment by veggiesaurus** [comment]
(edited from KS's original title to better indicate the underlying issue)

Protocol buffer messages that are being put into a `MultiMessageTask` sometimes have their `_event_buffer` partially or totally overwritten, resulting in errors when decoding messages. In some cases, the message simply fails to decode, in others it decodes with missing or incorrect fields.

I've printed out the raw memory array before and after corruption:
before: `[13, 0, 0, 0, 0, 18, 16, 1, 16, 0, 1, 0, 16, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 24, 1, 37, 0, 0, 48, 65]`
after: `[13, 0, 0, 0, 0, 21, 0, 0, 0, 0, 26, 1, 120, 26, 1, 121, 3, 181, 132, 156, 0, 0, 1, 24, 1, 37, 0, 0, 48, 65]`

**Comment by veggiesaurus** [comment]
the reason this is occurring is that we're reusing the uWS message buffer itself.The memory that `_event_buffer`points to is part of the larger `raw_message` buffer passed in `OnMessage`. By reusing that memory, we're assuming that uWS doesn't reuse it in any way, which is a bold assumption to make. 

I guess the only solution is to actually copy the message to a new buffer, and clean up this buffer after executing. 

Note that this is a critical bug, since we have no way of knowing which messages will be corrupted, and it will produce undefined behaviour.

**Comment by veggiesaurus** [comment]
@kswang1029 can you confirm whether this is fixed now?

**Comment by kswang1029** [comment]
for the missing tile issue, yes, I verified with an automated test few hundreds times. All pass.
