### ISSUE TITLE
[Session ID]The backend not check session ID

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#26]
In case user access the backend with an unknown ID, the backend creates a new session for it, so it always returns REGISTER_VIEWER_ACK.success = "true" and with no error message.

**Comment by veggiesaurus** [comment]
this is a good thing to check :+1: 

The expected behaviour (once resume support is built in) would be:
- If there is no session ID, then a new session is created
- If the session ID exists, and matches an existing session, that session is resumed
- If the session ID exists, but does not match an existing session, the session cannot be resumed, and the backend should return false.

(Note that the frontend doesn't currently support resuming sessions either, and the ICD will need to be expanded to deal with state transfers between frontend and backend on session resume)

**Comment by pford** [comment]
Opened issue #72 to handle all test failures, to be fixed in one branch/pull request. Closing this as duplicate.
