### ISSUE TITLE
Implement DS9 region import/export

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#287]
Subtask of #171, implement exporting region ids into file of specified type.

**Comment by pford** [comment]
Ready to test in release and dev.

**Comment by veggiesaurus** [comment]
> Ready to test in release and dev.

@pford should I merge my ds9 frnotend branch into `dev` and `release`?

**Comment by pford** [comment]
@veggiesaurus yes, please merge your branch.

**Comment by kswang1029** [comment]
Apologies for taking so long to get this test done due to travel and other business. I briefly tested the feature of ds9 region support in CARTA. Due to the richness of ds9 region format, I performed tests in two parts. All test files and image are attached.

1) import ds9 region files generated with ds9 to CARTA
a) same region in different coordinate systems and different coordinate formats
Here I just use "circle" region for this test. For each region file, there are two circles, one inside the image, the other outside the image.
- pixel [Loaded]
- ICRS, sexagesimal [Loaded]
- ICRS, degrees [Loaded]
- fk5, sexagesimal [Loaded]
- fk5, degrees [Loaded]
- fk4, sexagesimal [Loaded]
- fk4, degrees [Loaded]
- Galactic, sexagesimal [**Not loaded**]
![Screen Shot 2019-10-30 at 13.41.00.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/6019ff2b-d616-413c-8161-4bcd00fb390e)
- Galactic, degrees [Loaded]
- Ecliptic, sexagesimal [**Not loaded**]
![Screen Shot 2019-10-30 at 13.41.42.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/e4858a03-c66b-448a-8bf3-b66dcbcf02f9)
- Ecliptic, degrees [Loaded but in an incorrect place]

In addition, there seems to have errors in the coordinate of the region center. Not sure if this is due to coordinate transformation between different coordinate systems and/or insufficient precision in the region file from ds9.
![Screen Shot 2019-10-30 at 13.33.15.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/b34bb930-06c6-480c-a7f0-cda7e386ed0e)   

b) all possible ds9 regions in fk5 and in sexagesimal and degrees formats. Example file:

==============================
# Region file format: DS9 version 4.1
global color=green dashlist=8 3 width=1 font="helvetica 10 normal roman" select=1 highlite=1 dash=0 fixed=0 edit=1 move=1 delete=1 include=1 source=1
fk5
circle(275.1160555,-16.1652138,16.589")
ellipse(275.1165373,-16.1788074,33.178",16.589",359.99997)
box(275.1159396,-16.1928618,66.355",33.178",359.99997)
polygon(275.1206193,-16.2006948,275.1129420,-16.2039214,275.1110233,-16.2099120,275.1172614,-16.2078377)
line(275.1213416,-16.2156707,275.1095848,-16.2205106) # line=0 0
# vector(275.1211031,-16.2237347,53.426",332.24143) vector=1
# projection(275.1175054,-16.2347944,275.1035878,-16.2421687,4.908")
# segment(275.1016622,-16.1617593,275.0956657,-16.1730492)
# text(275.0942267,-16.1831868) text={Region}
point(275.0939871,-16.1937852) # point=circle
point(275.0942273,-16.2020796) # point=box
point(275.0937477,-16.2089916) # point=diamond
point(275.0942278,-16.2161340) # point=cross
point(275.0932682,-16.2223549) # point=x
point(275.0925485,-16.2294973) # point=arrow
point(275.0935086,-16.2359485) # point=boxcircle
# ruler(275.0846307,-16.1622205,275.0728761,-16.1684408) ruler=fk5 degrees
# compass(275.0786330,-16.1771964,10.807") compass=fk5 {N} {E} 1 1
# compass(275.0915870,-16.1509309,16.000") compass=fk5 {N} {E} 1 1
annulus(275.0779128,-16.1889467,10.368",20.736")
ellipse(275.0775122,-16.2039227,27.648",13.824",41.472",20.736",359.99997)
box(275.0773114,-16.2200507,55.296",27.648",82.944",41.472",359.99997)
panda(275.0769105,-16.2369467,359.99997,719.99997,4,10.368",20.736",1)
epanda(275.0589224,-16.1697450,359.99997,719.99997,4,27.648",13.824",41.472",20.736",1,359.99997)
bpanda(275.0565210,-16.1860647,359.99997,719.99997,4,55.296",27.648",82.944",41.472",1,359.99997)
==============================
Those commented out entries are default from ds9, not due to extra editing.

When importing this ds9 combo region file to CARTA, it works well. Non-supported regions are ignored.

2) export CARTA region in ds9 format and feed back to ds9 viewer
Region export from CARTA works but there appears position errors between world coordinate and image coordinate (pixel).
![Screen Shot 2019-10-30 at 13.44.23.png](https://images.zenhubusercontent.com/590bdf9f51aa2c30577d5260/839bc6d2-bbee-4e43-9a95-7c43685d38cd)


[https://app.zenhub.com/files/156166947/95f8d322-0cf8-462a-a959-5602c0856bf5/download](https://app.zenhub.com/files/156166947/95f8d322-0cf8-462a-a959-5602c0856bf5/download)

**Comment by veggiesaurus** [comment]
@kswang1029 if you load the same regions with CRTF (with the same number of decimal places as the DS9 file), do you get the same results?

**Comment by kswang1029** [comment]
@veggiesaurus good point. I will try.
