### ISSUE TITLE
[spectral profiler] performance degradation

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#33]
with the demo server: https://acdc0.asiaa.sinica.edu.tw:47568/
or the redhat server version: alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta3-redhat6.tar.gz

The performance of spectral profiler varies with different image formats.
Test images:
SgrB2-N.spw0.line.image
SgrB2-N.spw0.line.fits

With casa format, performance is excellent, but with FITS format, it takes longer to generate a spectral profile. This issue **does not** happen in the electron app on Mac. 

Could this be due to casacore?

**Comment by veggiesaurus** [comment]
FITS files are stored in a flat array, so reading a spectral profile requires reading a single pixel for each channel independently. CASA files use a tiling storage approach, so fewer reads are required (although reading the entire image might be slower). This would explain the performance difference between the two.

Maybe the files are getting more aggressively cached in memory on your Mac, which would explain why it doesn't seem to make a difference. Is the server using an SSD or HDD?

**Comment by kswang1029** [comment]
Could be. The test image is about 7GB and my laptop has 8GB ram. The demo server is using SSD, same as my laptop (I believe my laptop's SSD is faster due to PCIe). Maybe @pford can comment on how casacore accesses spectral profile in different image types?

**Comment by kswang1029** [comment]
with the current demo server: CARTA v1.1-alpha | frontend 48fd377 | backend 47854d0

With the image set_QA_performance/cube_A_01600_z04000.fits, it takes long time to see the spectral profile from each SET_CURSOR message. With the image set_QA_performance/cube_A_01600_z04000.image (casa format), spectral profiler is much responsive.

**Comment by veggiesaurus** [comment]
Not sure if there's a way around this in terms of speeding things up, since reading a spectral profile from a FITS file requires a random read for each channel, so it will always be far slower than CASA files (which in turn will be slower than HDF5 files with a rotated dataset). 

The only thing we can really do is to make sure that subsequent `SET_CURSOR` messages on the same file ID cancel calculations of currently running spectral profile tasks, and we can also use the `progress` field of the profile message to show partial profiles as the backend calculates them.

**Comment by kswang1029** [comment]
is it possible to parallelize region spectral profile calculations?

**Comment by veggiesaurus** [comment]
The bottleneck is all I/O, so it's unlikely to help much. Also have those threading issues with casacore, so not sure it's possible.

**Comment by kswang1029** [comment]
some info provided from Felix Stoehr about the possible solution to improve the performance of extracting spectra from FITS image @veggiesaurus @pford @markccchiang :

> In case it should really turn out that the performance of getting
spectra from ALMA FITS cubes is not fast enough for your liking, maybe
for that functionality you could use code from JVO's WebQL? I know that
they have written their own FITS reader for that very purpose which is
extremely fast. Chris Zapart told me that when they compute the average
spectrum of a circular region, they really go to each pixel, get the
spectrum and then at the end average everything together. If I
understand correctly, their code is available
https://github.com/jvo203/fits_web_ql

**Comment by veggiesaurus** [comment]
I've looked at their FITS reading code. My understanding of rust is not wonderful, but the approach seems to be simply reading from a 16-bit float cache of the entire image:

https://github.com/jvo203/fits_web_ql/blob/a97e7564f3f34f9e97f2b713e0217aa61da11fb5/src/fits.rs#L6270
(in this case, it looks like `data_f16` has a a size of W x H x D, so it's the entire cube. But not 100% sure if that's correct).

The extremely fast FITS reader looks like it uses a cached copy of the FITS file compressed using ZFP, so the actual cube is much smaller. This cached cube is then read in and decompressed over multiple threads. 

However, it would be good to chat to Chris about this in more detail. There are some very clever tricks used in WebQL. I'm pleasantly surprised to see ZFP, HEVC and some of the other things we're exploring in CARTA popping up in their code as well.

**Comment by veggiesaurus** [comment]
After compiling the latest version of FITSWebQL, running it and monitoring the memory usage, and going through the code, it looks like this is what's happening:
- Entire cube read into a _compressed_ array in memory (ZFP, using a fixed compression ratio of 4 bits per value, or to be more accurate, 64 bits per 4x4 block of pixels)
- Compressed cube written to disk, next time the file is loaded, the compressed cube is written

I've experimented with ZFP's fixed compression approach, and found it quite inaccurate. The reason this approach is used is because of the need for random access: the entire cube is stored in memory, but not in uncompressed format, so accessing any part of the cube requires looking up the block it resides in and decompressing the block. 

When calculating a spectral profile, it will access the compressed array and decompress the blocks as needed. This can be done in parallel, as the blocks all have a predictable size. This is a very fast process, but:
(a) it uses a lot of memory. Just to store the compressed cube, you need 1/8th of the cube size. So a 100 GB cube would take 12.5 GB. Not sure how scalable this is, unless you have lots of users all looking at the _same_ file
(b) it uses lossy compression with no error bounding (unlike our use of ZFP and a precision bounding, which puts an upper bound on the error of the compression), so it can't really be used for analytics or getting accurate results. They clearly believe it's fine for visualisation though. I guess that's where "Quick look" comes into it.
