### ISSUE TITLE
IMPORT_REGION_ACK.success == True even if region syntax in a file is invalid

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#343]
If there is invalid syntax in a region file, such as the following:

#CRTFv0 CASA Region Text Format version 0
symbol [[-123.8pix, **613.1**], .]
symbol [[-133.8pix, 613.1pix], .]

or

#CRTFv0 CASA Region Text Format version 0
symbol [[275.13653085deg, -16.17909524pix], .]
symbol [[275.13653085deg, -16.17909524deg], .]

currently all other valid regions are not loaded which is fine. However, IMPORT_REGION_ACK.success is still "True". 

The frontend also needs to show some error messages to users when IMPORT_REGION_ACK.success is False.

**Comment by veggiesaurus** [comment]
I suggest we stick to the strict definition of `success` that we're currently using, because `success` is a binary field. This makes error handling much simpler: Either a request succeeds (and we utilise the response) or it fails (and we display the error message). 

I think a warning is a more appropriate solution here. We can use the `ERROR_DATA` stream with a severity of `WARNING` to display a toast on the frontend

**Comment by kswang1029** [comment]
good idea. 👍

**Comment by pford** [comment]
@kswang1029 the error for your examples (mixed world and pixel coordinates) throws an exception in the casacode CRTF parser, so none of the regions are imported.  I can catch the exception, set success=false, set the error in the ACK message, and send ERROR_DATA for the Log widget.  The message specifies the CRTF line number where the error occurred.

**Comment by veggiesaurus** [comment]
@pford sorry, I think I misunderstood what @kswang1029 was saying. If the import completely fails, setting success=false and setting the error message is sufficient. I can use the error message in the response. No need for error data in this case. 

Perhaps if some succeed and others fail, we should return success and stream a warning?

**Comment by pford** [comment]
If any definitions in the CRTF file fail, the parser throws an exception; there is no partial success.  If this is unacceptable, I will have to discuss this change with Dave for a casacode pull request for carta release 1.3.  The carta Ds9Parser will behave as you describe; I am working on improving the error messages for failed regions.

For me, the pop-up error messages disappear too quickly to read e.g. `test_error.crtf line# 3: _init: Mixed world and pixel coordinates not supported` to know what and where the issue is.  With error data, the user can go to the log and see what happened.

(Side note: If I have other windows open which overlap the browser, I can miss the error entirely, or see something red but by the time I return to the browser the message is gone and there's no way to tell what happened.  This may be why users are interacting with carta after it disconnects from the server.)

**Comment by veggiesaurus** [comment]
Perhaps we should change to an alert popup for errors, and leave the toastr for warnings

**Comment by veggiesaurus** [comment]
> If this is unacceptable, I will have to discuss this change with Dave for a casacode pull request for carta release 1.3

I don't think this is too much of a problem. @kswang1029? How do other viewers handle situations where one region is poorly defined?

**Comment by kswang1029** [comment]
@veggiesaurus 
For casaviewer, if there is a poorly defined region, all other good regions are not loaded. At the bottom of the viewer GUI, there is a message in red specifying why.
For ds9, good regions can be still loaded. However, it seems there is no message somewhere specifying there is a bad region and why it is bad. This is a bit confusing as users may not know exactly how many regions should appear in the viewer.
