### ISSUE TITLE
Support for HDF5 mip-mapped datasets

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#347]
- [ ] Load mipmapped tile instead of downsampling
- [ ] Don't load whole full-res image
- [ ] Benchmark on ilifu large files
- [ ] Cache full-res tiles and fix spatial profiles

**Comment by Kechil** [comment]
Part of tiling implementation (need to be a dependency)

**Comment by confluence** [comment]
Task breakdown:

- [x] Add function(s) for loading mipmap data to the HDF5 image loader.
- [x] Split HDF5 image loader into header and implementation (refactoring; seems like a good time to do this)
- [x] Fix downsampled data height and width rounding bug in both backend and frontend.
- [x] Add an LRU tile cache for full-resolution tiles. This will be used for spatial profiles and full-resolution raster data, but only for HDF5 files (loading tiles from FITS files is inefficient). The cache should be cleared when the channel changes or the full image cache is populated.
- [x] Stop populating the full image cache when the image is loaded.
- [x] Functions on loader to determine if mipmaps should be used (mipmap layer is present) and if tile cache should be used (dataset is chunked). Treat older HDF5 files (without chunks and mipmaps) like non-HDF5 files.
- [x] When downsampled raster data is requested, populate the full image cache if it does not exist and downsample (non-HDF5), or load downsampled data from mipmap (HDF5).
- [x] When full-resolution tiled raster data is requested, use the full image cache if it exists (all files), otherwise populate the full image cache (non-HDF5), or populate the tile cache with the required tiles (HDF5) unless the number of tiles exceeds the cache capacity (unlikely but possible), in which case fall back to populating the full image cache.
- [x] Leave code for fetching untiled raster data (for animations) the way it is; it's going to be replaced.
- [x] When contours are requested, populate the full image cache (all files). Consider when this memory can be freed -- possibly when the channel changes, but only if we're not still displaying contours.
- [x]  When spatial profiles are requested, use the full image cache if it exists (all files), otherwise (non-HDF5) populate the full image cache or (HDF5) request the data from the tile cache
- [x] When calculation of the stats or the histogram for the full current channel is requested, populate the full image cache. This should never apply to HDF5 files, because their cube and channel stats and histograms are loaded from the loader and never trigger this code path.
- [x] Clear the tile cache when the stokes or channel changes
- [x] Invalidate (but don't load) the image cache when the stokes or channel changes
- [x] Load four tiles into the cache at a time (because one chunk is 512x512, and we need to read the whole chunk anyway).
- [x] Put back the dynamic minimum cache capacity (to increase the chances that spatial profiles can be satisfied entirely by cached tiles)
- [x] Send flags about file properties after opening the file.
- [ ] ~~Unit test the tile cache.~~ Deferred until we can integrate unit tests better.
- [x] Basic end-to-end test.
- [x] Make spatial profiles work like spectral profiles -- cancel obsolete requests.
- [x] Return shared pointers to tile data from the cache instead of copying the data
- [x] Revert unnecessarily complex changes to load image cache in multiple places. Always load it at the start as before for files without chunks or without mipmaps. Load on demand for contours.

(Checked items are not necessarily fully tested yet.)
