### ISSUE TITLE
Remove FITS hdus from file list and add to file info

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#357]
The file list takes too long with many FITS files because they are opened to find the image HDUs by name.  Instead, the file list should return file type (FITS) and the file size only.  The file info for each hdu should be sent in the file info message as a repeated field.

**Comment by kswang1029** [comment]
@pford @veggiesaurus Just to confirm, after the proposed change is implemented, there will be no HDU info in the file_list_response so initially users will just see a list of images (ie if there are 10 images, there will be just 10 entries in the list). If users click an image with multiple HDUs, then HDU info will be delivered to frontend with file_info_response. So frontend will need to use file_info_response to revise the file list in some way to let users select which HDU to load. Is the above description correct?

**Comment by veggiesaurus** [comment]
@kswang1029 yes. I think the simplest solution is to add a dropdown button in the file info / header panel that allows the user to select the hdu before loading

**Comment by pford** [comment]
This has been implemented in a backend branch, according to the changes in this [doc](https://docs.google.com/document/d/1nFa1OoMKz4a0i-VId6_1qXjkzxq1U7W6oPDen4JxjUk/edit).  The file_info_extended field in FileInfoResponse has been changed to a map with key=hdu (string) and value=FileInfoExtended for that hdu, including a computed_entries header entry for the extension name.

This needs a frontend branch or ICD test to test it, then can revise if needed.  Lowering the estimate since development is done.

**Comment by veggiesaurus** [comment]
> Lowering the estimate since development is done.

The estimate should keep track of the total amount of work required to solve an issue, so that we can get a better idea of how many story points go into a release.

**Comment by veggiesaurus** [comment]
> file list should return FITS type and the file size only.

@pford I assume you mean the file type, right? Returning the HDU types (image vs table) would require deeper inspection of the file, whereas just checking if it's a FITS file would require reading only the first 8 bytes of the image.

**Comment by Jordatious** [comment]
I have a related problem, that might actually be the same. When browsing directories with many of files (e.g. FITS images and catalogues, CASA / miriad / HDF5 files), CARTA browses through those directories very slowly. I thought that might be because it's reading those images so it can display the information about them in the "File Information" and "Header" tabs. It would be useful for the user to be able to disable this. Some file browsers also allow you to choose what type of file can be selected (see below). Perhaps a similar dropdown in the file browser that has 2-3 options would be useful (option 3 might be too complex):
1. CARTA image files (this reads the files and only displays image formats that CARTA can open, but takes longer)
2. Any file (this only reads the first 8 bytes of the files so will also display e.g. FITS catalogues - does this also work for non-FITS formats?). I'd prefer this by default.
3. Specific file types (e.g. only FITS or HDF5 when directory has a large number of other files. This should also probably read the first 8 bytes).

![image](https://user-images.githubusercontent.com/10542136/83528858-e6848080-a4e9-11ea-9946-70caf77146ea.png)
