### ISSUE TITLE
CARTA does not show correct velocities in CASA images 

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#377]
See files in www.nrao.edu/~jott/images-velocity.tar.gz

IRC10216_HC3N.cube_r0.5.image.fits  (fits image) 
IRC10216_HC3N.cube_r0.5.image  (CASA image)

NH3_3-3.2kms.clean.galmask.map.K5 (miriad image) 
NH3_3-3.2kms.clean.galmask.map.K5.fits (fits image)

The CASA file loads the data with the first plane at -0.8238 km/s 
The fits image is shown as -0.2832 km/s 

Looks like the velocity labeling in the CASA image display is not correct (in the CASA viewer the CASA image has the same value as the fits image -0.283221 km/s) 

Similar for the miriad image where the miriad image shows -249.9307 km/s but the fits image -250.0040 km/s  

Note that the MIRIAD images also shows the mask bug reported in a different ticket.

**Comment by jott3077** [comment]
(mask bug #347)

**Comment by jott3077** [comment]
I should mention that I haven't tested on HDF5 since I don't have such images.

**Comment by veggiesaurus** [comment]
@pford to ensure that the same header values are being sent to the frontend. If they are the same, then I'll look into what's causing the differences.

**Comment by pford** [comment]
This seems to be fixed with using the ImageFITSConverter to create FITS headers in file info (pull request #387, merged into dev).  Assigning to Kuo-Song to test.

**Comment by pford** [comment]
The differences are due to conversion/precision errors.  When the spectral axis CTYPE is FREQ then the CRVAL and CDELT values agree, so the frontend calculation results in the same velocity.

When CTYPE is VELO, the spectral axis values are converted to frequency for the casacore::SpectralCoordinate (causing the TabularCoordinate issue #373 ) so the FITS headers created from the image are FREQ.  The CRVAL and CDELT frequency values after this conversion differ between the FITS and MIRIAD images (not sure why yet).

**Comment by kswang1029** [comment]
I found a separate issue:
if there is a miriad image in NCP projection, its fits image after header unification in CARTA has the projection type as SIN. The same fits in ds9 is still in NCP projection. I wonder if there is any configurable parameter when we use casacore to generate the unified header?

**Comment by kswang1029** [comment]
@pford I wonder if this is because when the native CTYPE is VELO, the velocity spacing is uniform from first channel to last channel. However, if we convert it to FREQ, the frequency spacing is not uniform as the spacing is a function of frequency in the conversion. This is also the case vice versa.

**Comment by kswang1029** [comment]
@pford if CTYPE is FREQ in a miriad image, everything works fine in fits format both in CARTA and ds9. Test images: set_nativeMIRIAD

**Comment by kswang1029** [comment]
from miriad user manual:
         The spectral type to change to:
           FREQ: frequency,
           ENER: photon energy (linear with frequency),
           WAVN: wavenumber (linear with frequency),
           VRAD: radio velocity (linear with frequency),
           WAVE: wavelength,
           VOPT: optical velocity (linear with wavelength),
           ZOPT: redshift (linear with wavelength),
           AWAV: air wavelength (applicable to optical regime only),
           VELO: apparent radial velocity (relativistic),
           BETA: relativistic beta factor (= VELO/c).

The test image I have is in "VELO". If we convert it to FREQ and create FITS, everything works fine. If we convert it to "VRAD", the symptom remains.

**Comment by pford** [comment]
Created issue #404 for casacore::MIRIADImage issues, revising this issue for CASA images only.  @kswang1029 , please review whether this issue can be closed for CASA.

**Comment by jott3077** [comment]
MIRIAD also has a type FELO in addition to VELO. The difference is the Doppler definition: FELO is optical and VELO is radio.

**Comment by pford** [comment]
@veggiesaurus this is actually a frontend issue, as neither dev nor release shows the correct velocity when calculated from frequency using the CRVAL and RESTFRQ header values.  The headers are sent as a numeric value and a string value, e.g. "3.63924e+10" (release) and "3.639235e+10" (dev) due to different formatting, but the header entry type is FLOAT and the numeric values are identical.  This should result in identical velocities but does not.  When I changed the string format for the frequency headers in my release patch branch, the velocity changed!  The CASA image velocities now agree in release and dev, and agree with the FITS image in dev (its values are FREQ with the FITS header conversion), but this result is incorrect due to the rounding as if the string value were converted to numeric.

**Comment by pford** [comment]
I created frontend issue #653.  Angus is away.

**Comment by veggiesaurus** [comment]
[#653](https://github.com/CARTAvis/carta-frontend/issues/653) has a fix in the frontend, which solves the FITS / CASA discrepancy in @jott3077's test image set. 

There is still a Miraid / FITS discrepancy, though. But in this case, this is actually due to the header value differences. The backend is converting both files from a `CTYPE3` of `VELO-LSR` to `FREQ` and modifying the headers accordingly, which seems like an overreach.

**Comment by kswang1029** [comment]
@kswang1029 double check!

**Comment by veggiesaurus** [comment]
@kswang1029 can we close this?

**Comment by kswang1029** [comment]
yes we can. doing so now
