### ISSUE TITLE
add the environment variable needed for VNC to the startup 

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#379]
Given the problems with VNC, I have set myself an alias like: 

alias carta='LIBGL_ALWAYS_INDIRECT=1 carta'

That seems to work fine. But I wonder if the CARTA startup script could always set LIBGL_ALWAYS_INDIRECT=1 , so that vnc is not a special case anymore.  Maybe capture the variable at the start of CARTA, change to 1 and return to the previously set value at the shutdown of CARTA.

**Comment by veggiesaurus** [comment]
As far as I know, `LIBGL_ALWAYS_INDIRECT` only applies to the Mesa OpenGL driver, so setting this by default _shouldn't_ affect anything when running on a normal machine with an integrated or dedicated GPU, but @ajm-asiaa would have to do some testing to ensure that this doesn't affect anything else. Indirect rendering is considerably slower than direct rendering, so we don't want it to default to that when the user has a GPU available.

**Comment by Kechil** [comment]
Assigned to @ajm-asiaa to explore.

**Comment by kswang1029** [comment]
VNC is not an ideal environment for CARTA. The 2.0 release introduced a new and better way of using CARTA on a remote server. Also the controller version is introduced for site deployment. Can we close this?

**Comment by ajm-ska** [comment]
I originally tried to put it inside the AppImage so that it would used by default, but I wasn't able to get it to work. 
Another solution with the same effect for the Electron AppImage, or if using Chrome, is to add `--disable-gpu` at the end of the command.

But as we discovered, it seems to be a bad idea to disable GPU acceleration in CARTA as it significantly reduces performance on large images, particularly contour rendering and catalogs.

As @kswang1029 says, the new carta-controller is ideal for institute-wide deployment so that you can more easily access CARTA through your local web-browser, and not through VNC.

So I guess we can close this.
