### ISSUE TITLE
regression: missing per-frame histogram with 51200x51200 image

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#466]
@zarda found this issue

with set_QA_performance/cube_A/cube_A_51200_z00001.fits, histogram is missing
<img width="425" alt="Screen Shot 2020-03-11 at 9 37 02 PM" src="https://user-images.githubusercontent.com/20819712/76422943-ff94fe00-63e0-11ea-96a3-116d3a3b1fe4.png">

with set_QA_performance/cube_A/cube_A_38400_z00001.fits, it works fine
<img width="427" alt="Screen Shot 2020-03-11 at 9 38 36 PM" src="https://user-images.githubusercontent.com/20819712/76422975-10457400-63e1-11ea-8b63-9dbc907a7034.png">

potentially due to OpenMP replacement? @robsimmonds @veggiesaurus

**Comment by kswang1029** [comment]
With 80000x80000, it was loading then crashed.

**Comment by zarda** [comment]
Thank KSW for this report. 
The reason why the image in 80000x80000 makes backend crash may be due to the limitation of container size in casacore::Array. The maximum size for vector in 64bit system is 4611686018427387903. So suppose the limitation of std::vector in CARTA is not a reason.
While the carta::BasicStatsCalculator failing, the carta::BasicStatsCalculator::_num_pixels is zero. Will fix the limitation on CARTA first.

**Comment by veggiesaurus** [comment]
@kswang1029 does this need to be backported?

**Comment by kswang1029** [comment]
Yes, otherwise very large images cannot be loaded.

**Comment by veggiesaurus** [comment]
ok, @zarda please also make a PR targeting the release branch
