### ISSUE TITLE
backend hangs when requesting statistics

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#486]
v1.3 bug report from https://github.com/CARTAvis/carta/issues/14

To reproduce with the attached example images:
1) load testb.mom0.fits
2) launch statistics widget and we should see statistics but we don't. 
3) append testa.mom0.fits, and we will see the tile streaming indicator blinks forever

[Archive.zip](https://github.com/CARTAvis/carta-backend/files/4425703/Archive.zip)

**Comment by pford** [comment]
The brightness unit BUNIT for testb.mom0.fits is "JY/B*KM/S".  casacore::ImageStatistics determines whether the flux density can be computed by checking if the units are in Kelvin (contains "K" = true but the K is in KM/S) or if the image has one or more beams and units are per beam (contains "/beam" = false).  ImageStatistics tries to compute flux density but hangs somewhere, likely because it is confused by the units.  I don't know how to work around this since the only input to ImageStatistics is the ImageInterface object (SubImage for the current channel/stokes).

**Comment by veggiesaurus** [comment]
what if we add a manual check ourselves and remove the flux density stats requirement if the unit isn't correct?
