### ISSUE TITLE
separate performance related log when verbose=true

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#598]
performance related log should go to a dedicated file when verbose=true. This would give us a more concise log for analyzing issues/crash.

**Comment by veggiesaurus** [comment]
I think it'd be better to still keep it with stdout (easier for handling log files and buffers), but have a separate command line argument to enable performance logging. Perhaps `perflog=true`?

**Comment by veggiesaurus** [comment]
I think instead of separating log files (high risk for a backport), we should just add another command line argument "perflog". When set to true, we display performance logging in std out. When set to false, we don't (even if verbose=true). 

I'm not even sure we need to include this as an argument for the electron app, since it's purely for debugging purposes

**Comment by zarda** [comment]
I will apply the simple solution, to create a new command line argument "perflog". The performance message in std out will display. If we need to report these information on a specific log file, I could implement it then.
