### ISSUE TITLE
Compressed FITS file support

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#617]

**Comment by kswang1029** [comment]
test images are available via #682

**Comment by pford** [comment]
Issue #360 (fz) has been included in Epic #788 Carta FITS Support, which has an open PR #803 under review for release 2.0.  Issue #384 (fits.gz) has proven to be trickier and will be removed from #788/#803 for separate development, possibly pushed back to release 3.0 due to the code freeze and beta testing deadlines.
