### ISSUE TITLE
Backend should not block other threads during animation

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#66]
There is a mutex lock in AnimationQueue which blocks all other threads until the requested channel is complete, which kills performance during animation. The other threads should be used for downsampling, compression, histogram calculation, and spatial profiles.  There is an ICD message START_ANIMATION that the frontend does not currently send but might be useful for the backend to know whether the channel setting is temporary.

**Comment by pford** [comment]
Also noting here that cacheMutex should be reviewed (not needed if threads which might change channelCache are blocked anyway).

**Comment by veggiesaurus** [comment]
@pford Just saw this now, should have provided feedback weeks ago, sorry!

Our initial approach was to use the START_ANIMATION messages to control animations, rather than spamming the backend with SET_CHANNEL messages. However, I believe there were concerns about how the ASIAA backend would handle this, and large restructuring would be required, so we opted for the easier route. 

I agree that moving to this approach for animation would be helpful, because it would mean that we could separate this case from the case of a user switching channels manually, in which case only the latest channel is important. 

The other question is just _how_ important is it to attempt to process multiple messages simultaneously, given that many of the messages will end up blocking other messages anyway, and have complex interdependencies. A simpler starting point might be to have a message handling thread, a "channel" task thread and a "cube" task thread, since "channel" tasks (getting spatial profiles for the active channel, getting cursor values for the active channel, getting image data) are reasonably easily separable from "cube" tasks (getting cube histograms, spectral profiles, region stats) as the former make use of the channel cache, while the latter will require separate I/O.

**Comment by pford** [comment]
Redoing the message handling w.r.t threading is a major rewrite of the backend that needs to be done, but as an item on the release planning.  In the meantime, my thought was that during animation we don't need to cache the image data since the next message will change the channel anyway. Then each thread could handle its own data individually  (as long as the memory is sufficient), and just lock the Lattice during the data loading step.  It would still require some refactoring, as there are many dependencies on the channel cache vector.

**Comment by veggiesaurus** [comment]
@rwjsimmonds this seems to be fixed in your branch. Eventually we should still move to the animation approach specced in the ICD

**Comment by pford** [comment]
@kswang1029 , PR #115 should improve the animation performance in this issue.  If we have benchmarks you can re-run the tests, else just close this ticket.

**Comment by kswang1029** [comment]
@pford @rwjsimmonds Thanks!
The result from a quick and brief test of the PR#115 (Rob) is POSITIVE.
I tried a 12800x12800x100 image before and after PR#115 (I am using two different copies so should not have cache acceleration). Given 10 seconds, before the channel index goes to 5, and after the channel index goes to 10! So it is about a factor of 2 improvement. Note that I carefully did not trigger any SET_CURSOR messages (so no spatial/spectral profiles), so just to make sure the backend totally focuses on animation. 

Another test is that with a 9600x9600x100 cube, I count the time to have a animation loop to finish.
Before it is ~73seconds, and after it is ~55 seconds. 👍
