### ISSUE TITLE
refactor Constants.h

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#761]
`Constants.h` contains `#define` values for a whole host of different unrelated things. The problem with this approach is that changing anything in this file leads to huge recompiles, because loads of files include `Constants.h` (directly or indirectly). We should rather separate out these values into the appropriate headers (`Logger.h`, `Frame.h` etc)

**Comment by confluence** [comment]
I suggest that at the same time we refactor `Util.h` and `Util.cc`, for similar reasons. It's also a collection of unrelated functions, many of which are only used in one place. In some cases the presence of a particular function in `Util` rather than a more specific place is also complicating the refactoring of the constants.

**Comment by confluence** [comment]
I have bumped the estimate, since this is a bit more involved than previously thought. I will handle #744 in the same PR, since they are related tasks.
