### ISSUE TITLE
Improve --browser command-line argument behaviour

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#812]
Need to emulate behaviour found in jupyter-notebook (browser opening up as a separate process, etc).

**Comment by veggiesaurus** [comment]
assigning to @jolopezl. @confluence can help with the investigations.

**Comment by confluence** [comment]
I think examining what Jupyter / `webbrowser.open` / `subprocess.Popen` is doing in more detail will help us figure out what to do. We need to 1) launch the browser in a new session, 2) disown it so that closing the terminal doesn't kill it and 3) decide what to do with the output. My preference is to suppress it, for parity with the default browser command.

**Comment by jolopezl** [comment]
@confluence, @veggiesaurus: I tried several things for improving the browser command, including `boost::process` and system calls such as `fork()`, `setsid()`, and `execv()`, but none of them was actually the correct approach. Something along the lines of:
```
    pid_t pid = fork();
    if (pid < 0) {
        // fork fails
    } else if (pid == 0) {
        pid_t sid = setsid();
        exec(cmd.c_str(), NULL); // std::system(cmd.c_str());
    } else {
        // parent
    }
```
works relatively ok, but it changes the backend process, and it doesn't really exit when killing it as usual but stays in the background so that if you launch it again using the same port it will fail.

I suggest that we don't add more changes to the browser command now, and better understand what's the correct way of handling this.

PS: just noticed that I have a carta_backend zombie process now eating all CPU.
