### ISSUE TITLE
starting_port argument

### ISSUE THREAD

**Issue by ajm-ska** [CARTAvis/carta-backend#817]
At the moment, if using a shared installation of CARTA in a cluster environment, the carta_backend _must_ use port 3002 and upward. This might be a limitation on RHEL servers that have a firewall active by default. The sys-admin needs to open a range of ports, but there may be a preferred range of ports that are not 3002+.

After discussion with @veggiesaurus the best solution appears to be a new `starting_port` argument that could be put into the `/etc/carta/backend.json` config file.

It would simply set the port that the carta_backend begins to listen at. 

For example, the sys-admin could set it to 7777, and then go and open ports 7777-7799 in the firewall of their servers.

**Comment by o-smirnov** [comment]
I've got a question for the devs (or any knowledgable user) related to this. I'm running the 1.4 backend inside a container, port-forwarded over ssh. This all works perfectly fine, I specify ``--port X --fport Y`` for the HTTP and WebSocket ports on the backend, and invoke the URL as e.g. ``http://localhost:13010/?socketUrl=ws://localhost:13011``

And everything connects and loads up.

Looking at 2.0, I see the backend port options have changed:

```
  -p, --port <port>             manually set the HTTP and WebSocket port
                                (default: 3002 or nearest available port)
  -g, --grpc_port <port>        set gRPC service port
```

So is it a single unified HTP/WebSocket port now? (I didn't know that was possible.) And gRPC is something new to me.

I'm just trying to figure out which ports I must now forward (and how to form up the URL on the client side.)

**Comment by veggiesaurus** [comment]
@o-smirnov yes, the backend will now host the frontend code directly, on the same port. The grpc port is only needed if you want to control carta via the scripting interface, but this is still in active development as of 2.0.

**Comment by o-smirnov** [comment]
Excellent, so I only need to forward one port now, and the client-side URL is simply ``http://localhost:port``? Very neat!

**Comment by o-smirnov** [comment]
@veggiesaurus is there any way to pass in the authentication token programmatically, or is it always just chosen randomly?

**Comment by veggiesaurus** [comment]
> @veggiesaurus is there any way to pass in the authentication token programmatically, or is it always just chosen randomly?

You just need to set the `CARTA_AUTH_TOKEN` environmental variable. We decided this was a more secure approach than using a command line argument, because those will show up with `ps`.

> Excellent, so I only need to forward one port now, and the client-side URL is simply `http://localhost:port`? Very neat!

Yes, it simplifies things quite a bit. This is something we've been meaning to introduce for a while, but it required upgrading our websocket library to the latest version. The backend-hosting-frontend approach comes with a bunch of positive spinoffs too, such as making packaging much simpler and not requiring any other HTTP servers or wrapper scripts.

**Comment by o-smirnov** [comment]
Thanks, makes sense. I assume the standard ``uuid`` library is used for the token?

**Comment by veggiesaurus** [comment]
> Thanks, makes sense. I assume the standard `uuid` library is used for the token?

We use [`uuid`](https://www.npmjs.com/package/uuid) in the[ CARTA controller](https://carta-controller.readthedocs.io/en/release-2.0/) and [`libuuid`](https://linux.die.net/man/3/libuuid) for tokens generated by the backend. In particular, we use `uuid_generate_random` so that there's no information on the timestamp embedded.
