### ISSUE TITLE
Segmentation fault using spectral line query

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-backend#835]
I tried running a spectral line query for the first time since upgrading to 2.0.  It immediately segmentation faulted:

`/scratch/local/2762493/.mount_CARTA-DdZrZq/AppRun: line 18: 25445 Segmentation fault      (core dumped) $DIR/bin/carta_backend "$@"`

I was simply querying between 87.8 and 87.95 GHz with a couple modest-sized cubes open.

**Comment by veggiesaurus** [comment]
What distro is this? Could you try using the packaged version instead of the appimage?

**Comment by duidae** [comment]
This works for AppImage on RedHat/CentOS 7 platform(found by @ajm-asiaa):
`$ sudo yum install nss`

**Comment by veggiesaurus** [comment]
@keflavich what distro are you running this on? Did the above suggestion fix the issue?

**Comment by keflavich** [comment]
I was running on redhat 7.  I don't have rights to install software globally on the machine.  I haven't retried yet

**Comment by ajm-ska** [comment]
I don't think this is a CARTA issue as such.
CARTA uses the system's 'curl' command to query the spectral line database.  
The segmentation fault is due to curl failing. It is failing because the Network Security Services (nss) certificates are outdated. You are likely using an older RedHat 7 release such as RedHat 7.3 or 7.4 (`cat /etc/redhat-release`)
I bet 'curl' on that system is unable to connect to any HTTPS service. 
It can be fixed by updating the certificates with `sudo yum install nss`, but I understand you don't have root access.

**Comment by veggiesaurus** [comment]
> I don't think this is a CARTA issue as such.
> CARTA uses the system's 'curl' command to query the spectral line database.
> The segmentation fault is due to curl failing. It is failing because the Network Security Services (nss) certificates are outdated. You are likely using an older RedHat 7 release such as RedHat 7.3 or 7.4 (`cat /etc/redhat-release`)
> I bet 'curl' on that system is unable to connect to any HTTPS service.
> It can be fixed by updating the certificates with `sudo yum install nss`, but I understand you don't have root access.

the workaround for CARTA would be to not enforce HTTPS checking, as far as I know :thinking: Or to _attept_ HTTP connection and fall back on HTTP if it fails. A segfault isn't an ideal situation.

**Comment by kswang1029** [comment]
This issue will not be addressed as we are going to migrate the query from the backend to the frontend. Please refer to https://github.com/CARTAvis/carta-backend/issues/994 and https://github.com/CARTAvis/carta-frontend/issues/1755

Close this for now.
