### ISSUE TITLE
PR for adjusted CASA code

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#863]
Issue to track progress of the CASA PR which will allow us to remove a large chunk of code we've copied from casacode

**Comment by pford** [comment]
I opened a CASA ticket to change the imageanalysis code in the casa6 repo and looked at this in detail.  The goal of this issue is to remove code from CARTA that was copied from CASA imageanalysis.  However, the new imageanalysis ImageMoments function `lineMultiApply` was copied from casacore::LatticeApply to enable cancellation.  I think that the CASA reviewers will be as unhappy to add code copied from casacore as we are to have code copied from casacode.

`casacore::LatticeApply::lineMultiApply( )` is a static function, so there is no object on which to call `stopCalculation( )`.  I did some testing with the current backend dev code to see the impact of this function in the moment generator.  When requesting multiple moments 0-11 on a CASA image, of the ~1600 ms it took to calculate the moments, all but 15-20 ms was spent in `lineMultiApply` so checking for a stop flag outside of this function would be ineffective.  I also looked into calculating the moments individually to enable checking for the stop flag between moments, but as expected the performance of iterating through the input lattice multiple times was terrible at 6950 ms total or >4x slowdown.

The discussions in PR #791 and #602 (using HDF5 ZXY cube) suggest implementing an in-house moment generator, which might be a better strategy.

**Comment by veggiesaurus** [comment]
shall we close this issue @pford @kswang1029 ?

**Comment by kswang1029** [comment]
Ok from my side

**Comment by pford** [comment]
I agree.  I have already closed the CASA ticket as "Won't Do".

**Comment by pford** [comment]
Closed and replaced by #892
